apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
- ../../base
images:
- name: ghcr.io/ccq18/demo-hello
  newName: ghcr.io/ccq18/demo-hello
  newTag: sha-268de72
