apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hellospring
  namespace: apps
  labels:
    app.kubernetes.io/name: hellospring
    app.kubernetes.io/part-of: demo-hello-spring
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: hellospring
  strategy:
    blueGreen:
      activeService: hellospring
      previewService: hellospring-preview
      autoPromotionEnabled: false
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hellospring
        app.kubernetes.io/part-of: demo-hello-spring
    spec:
      imagePullSecrets:
        - name: ghcr-cred
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: hellospring
      containers:
        - name: hellospring
          image: ghcr.io/ccq18/demo-hello-spring:sha-initial
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: DB_HOST
              value: "10.120.0.6"
            - name: DB_PORT
              value: "3306"
            - name: DB_SSL_MODE
              value: "VERIFY_IDENTITY"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: hellospring-db
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hellospring-db
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: hellospring-db
                  key: DB_NAME
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
