apiVersion: v1
kind: Secret
metadata:
  name: hellospring-db
  namespace: apps
type: Opaque
stringData:
  DB_USER: hellospring_app
  DB_PASSWORD: hellospring_password_change_me
  DB_NAME: hellospring_app
